In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import gmaps.datasets

# Import API key
#from api_keys import gkey

#gmaps.configure(api_key='gkey')
gmaps.configure(api_key="")
gkey=''

In [2]:
weather_fire_2013_df = pd.read_csv('outputs/fireweather2013.csv', thousands=',')
fire_2013_df = pd.read_csv('outputs/fireweather2013clean.csv', thousands=',')

weather_fire_2015_df = pd.read_csv('outputs/fireweather2015.csv', thousands=',')
fire_2015_df = pd.read_csv('outputs/fireweather2015clean.csv', thousands=',')

weather_fire_2018_df = pd.read_csv('outputs_mergeable/weatherlat2018.csv', thousands=',')
fire_2018_df = pd.read_csv('outputs_mergeable/fire2018clean.csv', thousands=',')

weather_2013_full = pd.merge(weather_fire_2013_df, fire_2013_df, on="Latitude", how="outer")
#weather_2013_full.count()

weather_2015_full = pd.merge(weather_fire_2015_df, fire_2015_df, on="Latitude", how="outer")
#weather_2015_full.count()

weather_2018_full = pd.merge(weather_fire_2018_df, fire_2018_df, on="Latitude", how="outer")
#weather_2018_full.count()

In [3]:
weather_2013 = weather_2013_full.rename(columns={"Longitude_x": "Longitude", "Precipitation(MM)": "Precipitation"})
weather_2015 = weather_2015_full.rename(columns={"Longitude_x": "Longitude", "Precipitation(MM)": "Precipitation"})
weather_2018 = weather_2018_full.rename(columns={"Longitude_x": "Longitude", "Precipitation(MM)": "Precipitation"})

In [4]:
weather_2013 = weather_2013[["Name", "Latitude", "Longitude", "Acres Burned", "Date", "Temperature", "Humidity", "Precipitation", "Wind Speed", "Wind Gust"]]
weather_2015 = weather_2015[["Name", "Latitude", "Longitude", "Acres Burned", "Date", "Temperature", "Humidity", "Precipitation", "Wind Speed", "Wind Gust"]]
weather_2018 = weather_2018[["Name", "Latitude", "Longitude", "Acres Burned", "Date", "Temperature", "Humidity", "Precipitation", "Wind Speed", "Wind Gust"]]

In [5]:
weather_2013.dropna()

,Name,Latitude,Longitude,Acres Burned,Date,Temperature,Humidity,Precipitation,Wind Speed,Wind Gust
0,River Fire,36.602575,-118.016510,406.0,2013-02-24,41,25,0.0,10,16
1,Fawnskin Fire,34.288877,-116.941311,30.0,2013-04-20,76,23,0.0,5,8
2,Summit Fire,34.288877,-116.941311,3166.0,2013-04-20,76,23,0.0,5,8
3,Fawnskin Fire,34.288877,-116.941311,30.0,2013-05-01,77,26,0.0,11,17
4,Summit Fire,34.288877,-116.941311,3166.0,2013-05-01,77,26,0.0,11,17
...,...,...,...,...,...,...,...,...,...,...
140,Retek Fire,39.044200,-123.147800,82.0,2013-11-22,65,23,0.0,10,19
141,McCabe Fire,38.816700,-122.849800,3505.0,2013-11-22,66,18,0.0,12,21
142,Bruner Fire,39.044800,-122.765600,50.0,2013-11-23,64,27,0.0,7,12
143,Dam Fire,38.928900,-122.581800,23.0,2013-11-23,64,25,0.0,8,14
144,Grant Fire,37.342186,-121.717706,40.0,2013-12-31,59,58,0.0,2,4

In [6]:
weather_2015 = weather_2015.dropna(how='any')
weather_2015

,Name,Latitude,Longitude,Acres Burned,Date,Temperature,Humidity,Precipitation,Wind Speed,Wind Gust
0,Horse Fire,40.105882,-124.072042,146,8/18/15,77.0,73.0,0.0,3.0,5.0
1,Bald Fire,41.151300,-123.829200,20,6/10/15,65.0,82.0,0.0,5.0,8.0
2,Queen Fire,41.295667,-123.784067,158,7/24/15,78.0,67.0,0.0,3.0,5.0
3,Buck Fire,40.109300,-123.774000,16,7/28/15,90.0,52.0,0.0,6.0,11.0
4,Mendocino Lightning Fires,39.433010,-123.363160,50,7/30/15,91.0,55.0,0.7,4.0,6.0
...,...,...,...,...,...,...,...,...,...,...
93,Cutca Fire,33.383889,-116.868611,167,7/24/15,87.0,62.0,0.0,4.0,5.0
94,Wildcat Fire,32.942100,-116.853400,171,6/17/15,81.0,61.0,0.0,2.0,4.0
95,Lake Fire,33.214070,-116.734720,25,7/16/15,84.0,60.0,0.0,4.0,6.0
96,Anza Fire,33.573600,-116.538700,543,8/10/15,88.0,36.0,0.0,6.0,11.0
97,Park Fire,32.682547,-116.516840,25,7/24/15,89.0,40.0,0.0,5.0,8.0

In [7]:
weather_2018 = weather_2018.dropna(how='any')
weather_2018

,Name,Latitude,Longitude,Acres Burned,Date,Temperature,Humidity,Precipitation,Wind Speed,Wind Gust
0,Aqueduct Fire,35.924360,-119.940830,30.0,2018-04-12,64.0,48.0,0.1,15.0,21.0
1,Haycamp Fire,35.966890,-121.281850,50.0,2018-02-07,68.0,58.0,0.0,5.0,9.0
2,Pleasant Fire,37.402080,-118.502350,2070.0,2018-02-18,47.0,35.0,0.1,11.0,16.0
3,Grant Fire,37.738350,-121.603900,12.0,2018-05-14,74.0,67.0,0.0,5.0,7.0
4,Patterson Fire,33.629240,-117.059920,1261.0,2018-05-17,67.0,65.0,0.0,5.0,7.0
...,...,...,...,...,...,...,...,...,...,...
299,Sierra Fire,34.180750,-117.431840,147.0,2018-11-13,70.0,11.0,0.0,8.0,11.0
300,Niles Fire,37.611580,-121.941820,20.0,2018-11-14,71.0,22.0,0.0,3.0,4.0
301,Briggs Fire,34.301667,-119.099167,150.0,2018-11-15,70.0,38.0,0.0,5.0,8.0
302,Peak Fire,34.267348,-118.643816,186.0,2018-11-12,68.0,19.0,0.0,9.0,15.0
303,Bear Fire,37.128570,-122.120360,10.0,2018-11-16,68.0,31.0,0.0,2.0,3.0

In [8]:
# Store latitude and longitude in locations
locations = weather_2013[["Latitude", "Longitude"]]
weights = weather_2013["Acres Burned"]

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights)

# Add layer
fig.add_layer(heatmap_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Store latitude and longitude in locations
locations = weather_2013[["Latitude", "Longitude"]]
weights = weather_2013["Acres Burned"]

# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights)

# Add layer
fig.add_layer(heatmap_layer)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Store latitude and longitude in locations
locations = weather_2015[["Latitude", "Longitude"]]
weights = weather_2015["Acres Burned"]

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights)

# Add layer
fig.add_layer(heatmap_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Store latitude and longitude in locations
locations = weather_2015[["Latitude", "Longitude"]]
weights = weather_2015["Acres Burned"]

# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights)

# Add layer
fig.add_layer(heatmap_layer)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Store latitude and longitude in locations
locations = weather_2018[["Latitude", "Longitude"]]
weights = weather_2018["Acres Burned"]

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights)

# Add layer
fig.add_layer(heatmap_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Store latitude and longitude in locations
locations = weather_2018[["Latitude", "Longitude"]]
weights = weather_2018["Acres Burned"]

# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights)

# Add layer
fig.add_layer(heatmap_layer)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))